[package]
name = "rsg"
version = "0.1.0"
authors = ["meruri <yt.lyrs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
